### ISSUE TITLE
The plugin doesn't seem to work.

### ISSUE THREAD

**Issue by fkymnthanks** [yanntm/JITTAC#1]
I follewed the vedio to create models and map them to the source code. However, the relations can't generate.Can you check the consistency?

**Comment by yanntm** [comment]
hi,
sorry could you post a kind of reproducible procedure showing the issue ?
At least the steps you take and expected vs actual result. Better with a small example (e.g. a zip of the problematic project to help reproduce)

I'm willing to take a look if there is a bug, but I'm not an original author of the tool, I just wanted to use it and the original site did not work for recent eclipse so I repackaged it.

**Comment by fkymnthanks** [comment]
Thank you for your reply.
I followed the vedio(https://www.youtube.com/watch?v=BNqhp40PDD4) and used the jConverter.zip(https://sourceforge.net/projects/actool/files/) to operate.I think there should be relationships between the components and numbers on the lines.However, the numbers are all zero.I put the screenshot in the attachment.
Look forward to your reply and thank for your help.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanntm/JITTAC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月23日(星期三) 晚上10:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yanntm/JITTAC] The plugin doesn't seem to work. (#1)





 
hi,
 sorry could you post a kind of reproducible procedure showing the issue ?
 At least the steps you take and expected vs actual result. Better with a small example (e.g. a zip of the problematic project to help reproduce)
 
I'm willing to take a look if there is a bug, but I'm not an original author of the tool, I just wanted to use it and the original site did not work for recent eclipse so I repackaged it.

**Comment by yanntm** [comment]
hi so I did patch a bit the action that was incompatible with eclipse e4.

What works for me on the example project 
1. import project
2. right click project and select JITTAC->Enable analysis
3. restart eclipse

Not sure why we need to restart, but I hope this helps.

**Comment by fkymnthanks** [comment]
Thank you for your reply.
I have select JITTAC-&gt;Enable analysis.However, it still doen't work.I hava recorded the operation in the vedio.Can you help me see if there is any problem？Thank you for your help.


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "yanntm/JITTAC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月24日(星期四) 晚上6:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yanntm/JITTAC] The plugin doesn't seem to work. (#1)





 
hi so I did patch a bit the action that was incompatible with eclipse e4.
 
What works for me on the example project
  
import project
 
right click project and select JITTAC-&gt;Enable analysis
 
restart eclipse
  
Not sure why we need to restart, but I hope this helps.

**Comment by yanntm** [comment]
did you update the plugin ? The previous version "enable analysis" was broken.

**Comment by fkymnthanks** [comment]
Yes,I installed the plugin via the github address(https://yanntm.github.io/JITTAC/).




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "yanntm/JITTAC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月24日(星期四) 晚上7:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yanntm/JITTAC] The plugin doesn't seem to work. (#1)





 
did you update the plugin ? The previous version "enable analysis" was broken.

**Comment by yanntm** [comment]
It does work for me, I made a small video
https://www.youtube.com/watch?v=z4sjLsZ4Xss

**Comment by fkymnthanks** [comment]
It finally does work!I'm very grateful for your help!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanntm/JITTAC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月24日(星期四) 晚上8:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yanntm/JITTAC] The plugin doesn't seem to work. (#1)





 
It does work for me, I made a small video
 https://www.youtube.com/watch?v=z4sjLsZ4Xss

**Comment by yanntm** [comment]
cool !
